title: ITRI AI Hub
description: >
  A description of your site.
theme: "just-the-docs"

# Just the Docs settings
just_the_docs:
  logo: "/docs/assets/images/logo.png"
  nav:
    - title: "Home"
      url: "/"
      nav_order: 1
      children:
      - title: "Quick Start"
        url: "/docs/pages/quick-start"
        nav_order: 2
      - title: " - Setup Host Environment"
        url: "/docs/pages/quick-start/setup-environment"
        nav_order: 3
      - title: " - Download Image"
        url: "/docs/pages/quick-start/download-prebuilt-image"
        nav_order: 4
      - title: " - Flashing Image to Board"
        url: "/docs/pages/quick-start/flash-image"
        nav_order: 5
      - title: "ML Engine"
        url: "/docs/pages/engine"
        nav_order: 6
      - title: " - CUDA"
        url: "/docs/pages/engine/engine1/"
        nav_order: 7
      - title: " - ROCm"
        url: "/docs/pages/engine/engine2/"
        nav_order: 8
      - title: "Model Delegation"
        url: "/docs/pages/delegation"
        nav_order: 9
      - title: " - TensorRT"
        url: "/docs/pages/delegation/delegation1/"
        nav_order: 10
      - title: " - NeuronPilot"
        url: "/docs/pages/delegation/delegation2/"
        nav_order: 11
      - title: " - ArmNN"
        url: "/docs/pages/delegation/delegation3/"
        nav_order: 12
      - title: "Use Case"
        url: "/docs/pages/usecase"
        nav_order: 13
      - title: " - Case 1"
        url: "/docs/pages/usecase/usecase1/"
        nav_order: 14
      - title: " - Case 2"
        url: "/docs/pages/usecase/usecase2/"
        nav_order: 15