title: ITRI AI Hub
description: >
  A description of your site.
theme: "just-the-docs"

# Just the Docs settings
just_the_docs:
  logo: "/assets/images/logo.png"
  nav_order: 1
  nav:
    - title: "Home"
      url: "/docs/"
      nav_order: 1
    - title: "About"
      url: "/docs/about/"
      nav_order: 2
    - title: "Use Case"
      url: "/docs/usecase/"
      nav_order: 3
      children:
        - title: "Use Case 1"
          url: "/docs/usecase/usecase1/"
          nav_order: 1
        - title: "Use Case 2"
          url: "/docs/usecase/usecase2/"
          nav_order: 2
