title: Developer Zone
description: >
  A description of your site.
theme: "just-the-docs"
color_scheme: light_blue
just_the_docs:
  nav:
    - url: "/"
      children:
      - url: "/docs/genio-evk.md"
      - url: "/docs/genio-evk/flash_tool.md"
      - url: "/docs/genio-evk/neuronpilot.md"
      - url: "/docs/genio-evk/bsp_for_ubuntu.md"
      - url: "/docs/hailo.md"
      - url: "/docs/ryzen.md"
      - url: "/docs/jetson-evk.md"
