title: Developer Zone
description: >
  A description of your site.
theme: "just-the-docs"

# Just the Docs settings
just_the_docs:
  logo: "/docs/assets/images/logo.png"
  nav:
    - title: "Home"
      url: "/"
      nav_order: 1
      children:
      - title: "Get Started"
        url: "/docs/pages/get-started.md"
        nav_order: 2
      - title: "　-　Genio EVKs"
        url: "/docs/pages/get-started/genio-evk.md"
        nav_order: 3
      - title: "　-　I-Pi SMARCs"
        url: "/docs/pages/get-started/ipi-smarc.md"
        nav_order: 4
      - title: "　-　RaspberryPis"
        url: "/docs/pages/get-started/raspberrypi.md"
        nav_order: 5
      - title: "　-　Jetson EVKs"
        url: "/docs/pages/get-started/jetson-evk.md"
        nav_order: 6

      - title: "Workstation"
        url: "/docs/pages/workstation.md"
        nav_order: 10
      - title: "　-　CUDA"
        url: "/docs/pages/workstation/cuda.md"
        nav_order: 11
      - title: "　-　ROCm"
        url: "/docs/pages/workstation/rocm.md"
        nav_order: 12
      - title: "　-　Open VINO"
        url: "/docs/pages/workstation/openvino.md"
        nav_order: 13
      - title: "　-　Ryzen AI"
        url: "/docs/pages/workstation/ryzen-ai.md"
        nav_order: 14

      - title: "Compiler"
        url: "/docs/pages/compiler.md"
        nav_order: 20
      - title: "　-　Data Compiler"
        url: "/docs/pages/compiler/data-compiler.md"
        nav_order: 21
      - title: "　-　Vitis AI"
        url: "/docs/pages/compiler/vitis-ai.md.md"
        nav_order: 22
      - title: "　-　NeuronPilot"
        url: "/docs/pages/compiler/neuronpilot.md"
        nav_order: 24

      - title: "Runtime SDKs"
        url: "/docs/pages/runtime.md"
        nav_order: 30
      - title: "　-　Kleidi AI"
        url: "/docs/pages/runtime/kleidi.md"
        nav_order: 31
      - title: "　-　ArmNN"
        url: "/docs/pages/runtime/armnn.md"
        nav_order: 33
      - title: "　-　HailoRT"
        url: "/docs/pages/runtime/hailort.md"
        nav_order: 34
      - title: "　-　TensorRT"
        url: "/docs/pages/runtime/tensorrt.md"
        nav_order: 35
      - title: "　-　NeuronRT"
        url: "/docs/pages/runtime/neuronrt.md"
        nav_order: 36
  
      - title: "Benchmarks"
        url: "/docs/pages/benchmark.md"
        nav_order: 40

      - title: "Use Case"
        url: "/docs/pages/usecase.md"
        nav_order: 50
      - title: "　-　Case 1"
        url: "/docs/pages/usecase/usecase1.md"
        nav_order: 51
