title: Developer Zone
description: >
  A description of your site.
theme: "just-the-docs"

# Just the Docs settings
just_the_docs:
  logo: "/docs/assets/images/logo.png"
  nav:
    - title: "How to Get Started?"
      url: "/docs/get-start.md"
      nav_order: 1
      children:
      - title: "Genio Evaluation Kits"
        url: "/docs/genio-evk.md"
        nav_order: 2
      - title: "　-　Step1."
        url: "/docs/genio-evk/step1.md"
        nav_order: 3
    