title: ITRI AI Hub
description: >
  A description of your site.
theme: "just-the-docs"

# Just the Docs settings
just_the_docs:
  logo: "/docs/assets/images/logo.png"
  nav:
    - title: "Home"
      url: "/"
      nav_order: 1
      children:
      - title: "About"
        url: "/docs/pages/about/"
        nav_order: 2
      - title: "Use Case"
        url: "/docs/pages/usecase"
        nav_order: 3
      - title: " - Case 1"
        url: "/docs/pages/usecase1/"
        nav_order: 4
      - title: " - Case 2"
        url: "/docs/pages/usecase2/"
        nav_order: 5