title: ITRI AI Hub
description: >
  A description of your site.
theme: "just-the-docs"

# Just the Docs settings
just_the_docs:
  logo: "/docs/assets/images/logo.png"
  nav:
    - title: "Home"
      url: "/"
      nav_order: 1
      children:
      - title: "Get Started"
        url: "/docs/pages/get-started"
        nav_order: 2
      - title: "　-　Genio EVKs"
        url: "/docs/pages/get-started/genio-evk.md"
        nav_order: 3
      - title: "　-　I-Pi SMARCs"
        url: "/docs/pages/get-started/ipi-smarc.md"
        nav_order: 4
      - title: "　-　RaspberryPis"
        url: "/docs/pages/get-started/raspberrypi.md"
        nav_order: 5
      - title: "　-　Jetson EVKs"
        url: "/docs/pages/get-started/jetson-evk.md"
        nav_order: 6
      - title: "ML Engine"
        url: "/docs/pages/ml-engine.md"
        nav_order: 7
      - title: "　-　CUDA"
        url: "/docs/pages/ml-engine/cuda.md"
        nav_order: 8
      - title: "　-　ROCm"
        url: "/docs/pages/ml-engine/rocm.md"
        nav_order: 9
      - title: "　-　Kleidi AI"
        url: "/docs/pages/ml-engine/kleidi.md"
        nav_order: 10
      - title: "Delegation"
        url: "/docs/pages/delegation"
        nav_order: 11
      - title: "　-　Data Compiler"
        url: "/docs/pages/delegation"
        nav_order: 12
      - title: "Runtime Accelerator"
        url: "/docs/pages/runtime"
        nav_order: 13
      - title: "　-　NeuronPilot"
        url: "/docs/pages/runtime/neuronpilot.md"
        nav_order: 14
      - title: "　-　ArmNN"
        url: "/docs/pages/runtime/armnn.md"
        nav_order: 15
      - title: "　-　HailoRT"
        url: "/docs/pages/runtime/hailort.md"
        nav_order: 16
      - title: "　-　TensorRT"
        url: "/docs/pages/runtime/tensorrt.md"
        nav_order: 17
      - title: "Benchmarks"
        url: "/docs/pages/benchmark"
        nav_order: 18
      - title: "Use Case"
        url: "/docs/pages/usecase"
        nav_order: 19
      - title: "　-　Case 1"
        url: "/docs/pages/usecase/usecase1/"
        nav_order: 20
