title: ITRI AI Hub
description: >
  A description of your site.
theme: "just-the-docs"

# Just the Docs settings
just_the_docs:
  logo: "/docs/assets/images/logo.png"
  nav:
    - title: "Home"
      url: "/"
      nav_order: 1
      children:
      - title: "Quick Start"
        url: "/docs/pages/quick-start"
        nav_order: 2
      - title: " - Setup Host Environment"
        url: "/docs/pages/quick-start/setup-environment"
        nav_order: 3
      - title: " - Download Prebuild Images"
        url: "/docs/pages/quick-start/download-images"
        nav_order: 4
      - title: " - Flashing Image to Board"
        url: "/docs/pages/quick-start/installation"
        nav_order: 5
      - title: " - Deployment"
        url: "/docs/pages/quick-start/deployment"
        nav_order: 6
      - title: "Use Case"
        url: "/docs/pages/usecase"
        nav_order: 7
      - title: " - Case 1"
        url: "/docs/pages/usecase/usecase1/"
        nav_order: 8
      - title: " - Case 2"
        url: "/docs/pages/usecase/usecase2/"
        nav_order: 9