title: Developer Zone
description: >
  A description of your site.
theme: "just-the-docs"

just_the_docs:
  nav:
    - url: "/"
      nav_order: 1
      children:
      - url: "/docs/genio-evk.md"
        nav_order: 2
      - url: "/docs/genio-evk/step1.md"
        nav_order: 3
    