title: Developer Zone
description: >
  A description of your site.
theme: "just-the-docs"
color_scheme: light_blue
just_the_docs:
  custom_css:
    - "/docs/assets/css/custom.css"
  nav:
    - url: "/"
      children:
      - url: "/docs/genio-evk.md"
      - url: "/docs/genio-evk/step1.md"
      - url: "/docs/genio-evk/step2.md"
      - url: "/docs/genio-evk/step3.md"
      - url: "/docs/hailo.md"
      - url: "/docs/ryzen.md"
      - url: "/docs/jetson-evk.md"
