yolov8l-pose:
- /model.22/cv4.2/cv4.2.2/Conv
- /model.22/cv4.1/cv4.1.2/Conv
- /model.22/cv4.0/cv4.0.2/Conv
- /model.22/cv3.2/cv3.2.2/Conv
- /model.22/cv3.1/cv3.1.2/Conv
- /model.22/cv3.0/cv3.0.2/Conv
- /model.22/cv2.2/cv2.2.2/Conv
- /model.22/cv2.1/cv2.1.2/Conv
- /model.22/cv2.0/cv2.0.2/Conv
yolov8m-pose:
- /model.22/cv4.2/cv4.2.2/Conv
- /model.22/cv4.1/cv4.1.2/Conv
- /model.22/cv4.0/cv4.0.2/Conv
- /model.22/cv3.2/cv3.2.2/Conv
- /model.22/cv3.1/cv3.1.2/Conv
- /model.22/cv3.0/cv3.0.2/Conv
- /model.22/cv2.2/cv2.2.2/Conv
- /model.22/cv2.1/cv2.1.2/Conv
- /model.22/cv2.0/cv2.0.2/Conv
yolov8n-pose:
- /model.22/cv4.2/cv4.2.2/Conv
- /model.22/cv4.1/cv4.1.2/Conv
- /model.22/cv4.0/cv4.0.2/Conv
- /model.22/cv3.2/cv3.2.2/Conv
- /model.22/cv3.1/cv3.1.2/Conv
- /model.22/cv3.0/cv3.0.2/Conv
- /model.22/cv2.2/cv2.2.2/Conv
- /model.22/cv2.1/cv2.1.2/Conv
- /model.22/cv2.0/cv2.0.2/Conv
yolov8s-pose:
- /model.22/cv4.2/cv4.2.2/Conv
- /model.22/cv4.1/cv4.1.2/Conv
- /model.22/cv4.0/cv4.0.2/Conv
- /model.22/cv3.2/cv3.2.2/Conv
- /model.22/cv3.1/cv3.1.2/Conv
- /model.22/cv3.0/cv3.0.2/Conv
- /model.22/cv2.2/cv2.2.2/Conv
- /model.22/cv2.1/cv2.1.2/Conv
- /model.22/cv2.0/cv2.0.2/Conv
yolov8x-pose:
- /model.22/cv4.2/cv4.2.2/Conv
- /model.22/cv4.1/cv4.1.2/Conv
- /model.22/cv4.0/cv4.0.2/Conv
- /model.22/cv3.2/cv3.2.2/Conv
- /model.22/cv3.1/cv3.1.2/Conv
- /model.22/cv3.0/cv3.0.2/Conv
- /model.22/cv2.2/cv2.2.2/Conv
- /model.22/cv2.1/cv2.1.2/Conv
- /model.22/cv2.0/cv2.0.2/Conv